[package]
name = "s3-lifecycle"
version = "0.1.0"
edition = "2015"

[dependencies]
rusoto_core = "0.42"
rusoto_s3 = "0.42"
clap = "2.32"
tokio-core = "0.1"
futures = "0.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
